name: Tfvaegan_AWA2
model_type: Tfvaegan
num_gpu: 1
manual_seed: 9182
wandb: False

datasets:
  name: AWA2
  type: ZSLDataset
  dataroot: datasets

train:
  num_workers: 8
  batch_size: 64
  num_epoch: 800
  betas: [0.5, 0.999]

network:
  gan:
    lr: 0.0001
    image_embedding: res101_ft
    class_embedding: att
    syn_num: 1800
    res_size: 2048
    att_size: 85
    latent_dim: 85
    layer_sizes: [2133, 4096] # 2048 + latent_dim
    ndh: 4096
    ngh: 4096
    gamma_g: 10
    gamma_d: 10
    num_class: 50
    lambda: 10
    critic_iter: 5
    noise: False

  decoder:
    lr: 0.00001
    layer_sizes: [4096, 2048]
    recons_weight: 1
    freeze: True

  classifier:
    lr: 0.001
    gzsl: True

  feedback:
    lr: 0.00001
    a1: 0.1
    a2: 0.1
    feedback_loop: 2
