name: tfVAEGAN_CUB
model_type: tfVAEGAN
num_gpu: 1
manual_seed: 3483

datasets:
  name: CUB
  type: ZSLDataset
  dataroot: datasets

train:
  num_workers: 8
  batch_size: 64
  num_epoch: 300

network:
  gan:
    lr: 0.01
    image_embedding: res101
    class_embedding: att
    syn_num: 100
    res_size: 2048
    att_size: 1024
    latent_dim: 312
    ndh: 4096
    ngh: 1024
    gamma_g: 10
    gamma_d: 10
    num_class: 200
    lambda: 10
    critic_iter: 5
    noise: True

  decoder:
    lr: 0.001
    recons_weight: 0.01

  classifier:
    lr: 0.001
    gzsl: True

  feedback:
    lr: 0.00001
    a1: 1
    a2: 1
    feedback_loop: 2
