name: tfVAEGAN_CUB
model_type: tfVAEGAN
num_gpu: 1
manual_seed: 3483

datasets:
  name: CUB
  type: ZSLDataset
  dataroot: datasets
 
train:
  num_workers: 8
  batch_size: 64
  num_epoch: 300

optimizer:
  adam:
    betas: [0.5, 0.999]

network:
  gan:
    lr: 0.0001
    image_embedding: res101
    class_embedding: att
    syn_num: 300
    res_size: 2048
    att_size: 312
    latent_dim: 312
    layer_sizes: [8192, 4096]
    ndh: 4096
    ngh: 4096
    gamma_g: 10
    gamma_d: 10
    num_class: 200
    lambda: 10
    critic_iter: 5
    noise: True

  decoder:
    layer_sizes: [4096, 8192]
    lr: 0.0001
    recons_weight: 0.01

  classifier:
    lr: 0.001
    gzsl: True

  feedback:
    lr: 0.00001
    a1: 1
    a2: 1
    feedback_loop: 2
