name: Tfvaegan_SUN
model_type: Tfvaegan
num_gpu: 1
manual_seed: 4115
wandb: False

datasets:
  name: SUN
  type: ZSLDataset
  dataroot: datasets

train:
  num_workers: 8
  batch_size: 64
  num_epoch: 400
  betas: [0.5, 0.999]

network:
  gan:
    lr: 0.001
    image_embedding: res101
    class_embedding: att
    syn_num: 400
    res_size: 2048
    att_size: 102
    latent_dim: 102
    layer_sizes: [2150, 4096] # 2048 + latent_dim
    ndh: 4096
    ngh: 4096
    gamma_g: 1
    gamma_d: 1
    num_class: 717
    lambda: 10
    critic_iter: 5
    noise: True

  decoder:
    lr: 0.0001
    layer_sizes: [4096, 2048]
    recons_weight: 0.01
    freeze: False

  classifier:
    lr: 0.0005
    gzsl: True

  feedback:
    lr: 0.0001
    a1: 0.1
    a2: 0.01
    feedback_loop: 2
